import { Dimensions } from 'react-native';
const { width: windowWidth } = Dimensions.get('window');

export const $pt = (value: number) => (value * windowWidth) / 375;
const scale = 4;
export const Theme = {
  scale,
  windowWidth,
  colorBrand: '#8f432e',
  colorBrandSecond: '#8f432e',
  bgColorPrimary: '#EEE',
  bgColorSecondary: '#EEE',
  colorDivide: '#999',
  colorSuccess: 'red',
  colorWarning: 'yellow',
  colorInfo: '#999',
  colorWhite: '#FFF',
  colorToastBg: '#222',
  shoadowStyle1: {},
  showdowStyle2: {},
  showdowStyle3: {},
  fontColorPrimary: '#222',
  fontColorSecond: '#444',
  fontColorTertiary: '#666',
  fontColorQuaternary: '#999',
  fontSizeSuper: 50,
  fontSizeUltra: 40,
  fontSizeLarge: 30,
  fontSizeDefault: 15,
  fontSizeTitle: 20,
  fontSizeDesc: 13,
  fontSizeSmalll: 12,
  borderRadiusSmall: scale,
  borderRadiusMiddle: scale * 2,
  borderRadiusLarge: scale * 3,
  borderRadiusUltra: scale * 4,
  sizeToastHeight: scale * 12,
  sizeTabHeight: scale * 16,
  sizeCellHeight: scale * 11,
  sizeHeaderHeight: scale * 12,
  sizeIconSmallHeight: scale * 4,
  sizeIconMiddleHeight: scale * 6,
  sizePagePadding: scale * 4,
  sizeCardPadding: scale * 4,
  sizeTitlePadding: scale * 2,
  sizeTagPadding: scale * 1,
  sizeTextPadding: scale * 1,
  sizeFullButtonWidth: $pt(375 - 44),
  sizeFullButtonHeight: scale * 11,
};
